Repository giantswarm/releases, pull requests merged in 2024-08, with the labels that each got.

#1340 Add release request for new cert-exporter version
  capa/requests.yaml
Labels: skip/ci

#1341 Set Cilium requests for CAPI releases
  azure/requests.yaml
  capa/requests.yaml
Labels: skip/ci

#1342 Update requests.yaml for CAPA and CAPZ
  azure/requests.yaml
  capa/requests.yaml
Labels: skip/ci

#1345 CAPI: Request `security-bundle` >= v1.8.1 for > v29.0.0.
  azure/requests.yaml
  capa/requests.yaml
Labels: skip/ci

#1347 CAPZ: Request `observability-bundle` >= v1.6.1.
  azure/requests.yaml
Labels: skip/ci

#1349 CAPA: Deprecate multiple releases.
  capa/releases.json
  capa/v25.1.0/release.yaml
  capa/v26.0.0/release.yaml
  capa/v27.0.0/release.yaml
  capa/v28.0.0/release.yaml
  capa/v28.0.1/release.yaml
  capa/v28.1.0/release.yaml
  capa/v29.0.0/release.yaml
Labels: area/kaas

#1350 CAPA: Archive v26.0.0.
  README.md
  capa/archived/v26.0.0/README.md
  capa/archived/v26.0.0/announcement.md
  capa/archived/v26.0.0/kustomization.yaml
  capa/archived/v26.0.0/release.yaml
  capa/kustomization.yaml
  capa/releases.json
Labels: topic/capi, area/kaas, skip/ci

#1351 CAPA: Archive release v27.0.0
  README.md
  capa/archived/v27.0.0/README.md
  capa/archived/v27.0.0/announcement.md
  capa/archived/v27.0.0/kustomization.yaml
  capa/archived/v27.0.0/release.yaml
  capa/kustomization.yaml
  capa/releases.json
Labels: topic/capi, area/kaas

#1356 Update security-bundle requests for v29.1.x and above
  azure/requests.yaml
  capa/requests.yaml
Labels: skip/ci
