Repository giantswarm/releases, pull requests merged in 2024-09, with the labels that each got.

#1358 Docs: Update CAPA version.
  .github/pull_request_template.md
  README.md
Labels: skip/ci

#1360 CAPA: Archive v28.1.0.
  README.md
  capa/archived/v28.1.0/README.md
  capa/archived/v28.1.0/announcement.md
  capa/archived/v28.1.0/kustomization.yaml
  capa/archived/v28.1.0/release.yaml
  capa/kustomization.yaml
  capa/releases.json
Labels: topic/capi, area/kaas

#1381 Go: Clean dependencies.
  go.mod
  go.sum
  releases_test.go
  renovate.go
  sdk/go.mod
  sdk/go.sum
  tools.go
Labels: skip/ci

#1368 CAPA: Archive v28.0.1.
  README.md
  capa/archived/v28.0.1/README.md
  capa/archived/v28.0.1/announcement.md
  capa/archived/v28.0.1/kustomization.yaml
  capa/archived/v28.0.1/release.diff
  capa/archived/v28.0.1/release.yaml
  capa/kustomization.yaml
  capa/releases.json
Labels: topic/capi, area/kaas, skip/ci

#1382 GitHub: Improve release creation.
  .github/workflows/releases.yaml
Labels: skip/ci

#1414 CAPA: Release v26.1.1.
  README.md
  capa/kustomization.yaml
  capa/releases.json
  capa/v26.1.1/README.md
  capa/v26.1.1/announcement.md
  capa/v26.1.1/kustomization.yaml
  capa/v26.1.1/release.diff
  capa/v26.1.1/release.yaml
Labels: skip/ci

#1415 CAPA: Release v27.1.1.
  README.md
  capa/kustomization.yaml
  capa/releases.json
  capa/v27.1.1/README.md
  capa/v27.1.1/announcement.md
  capa/v27.1.1/kustomization.yaml
  capa/v27.1.1/release.diff
  capa/v27.1.1/release.yaml
Labels: skip/ci

#1416 CAPA: Release v28.1.2.
  README.md
  capa/kustomization.yaml
  capa/releases.json
  capa/v28.1.2/README.md
  capa/v28.1.2/announcement.md
  capa/v28.1.2/kustomization.yaml
  capa/v28.1.2/release.diff
  capa/v28.1.2/release.yaml
Labels: skip/ci

#1418 CAPA: Archive v28.0.0.
  README.md
  capa/archived/v28.0.0/README.md
  capa/archived/v28.0.0/announcement.md
  capa/archived/v28.0.0/kustomization.yaml
  capa/archived/v28.0.0/release.yaml
  capa/kustomization.yaml
  capa/releases.json
Labels: area/kaas, skip/ci

#1419 CAPA: Release v29.2.0.
  README.md
  capa/kustomization.yaml
  capa/releases.json
  capa/v29.2.0/README.md
  capa/v29.2.0/announcement.md
  capa/v29.2.0/kustomization.yaml
  capa/v29.2.0/release.diff
  capa/v29.2.0/release.yaml
Labels: skip/ci

#1389 CAPZ: Release v29.1.0.
  README.md
  azure/kustomization.yaml
  azure/releases.json
  azure/v29.1.0/README.md
  azure/v29.1.0/announcement.md
  azure/v29.1.0/kustomization.yaml
  azure/v29.1.0/release.diff
  azure/v29.1.0/release.yaml
Labels: skip/ci
